'use client'
import { useState, useEffect } from 'react'
import { ReportData } from '@/app/lib/types'
import { PhotoAnalysisResult } from '@/app/api/analyze-photos/route'
import ScoreCircle from './ScoreCircle'
import { APP_VERSION } from '@/app/lib/version'
import ReportSection from './ReportSection'
import DownloadPdfButton from './DownloadPdfButton'
import PhotoUploader from './PhotoUploader'

interface Props {
  data: ReportData
  onReset: () => void
  plan?: string
  isDemo?: boolean
  listingUrl?: string
  initialPhotoResults?: PhotoAnalysisResult | null
  initialPhotoPreviews?: string[] | null
}

function buildTextReport(d: ReportData, listingUrl?: string): string {
  const divider = '─'.repeat(40)
  const lines: string[] = [
    `LISTINGIQ REPORT`,
    `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    ...(listingUrl ? [`Listing: ${listingUrl}`] : []),
    divider,
    ``,
    `OVERALL SCORE: ${d.overallScore}/100`,
    `${d.summary}`,
    `Improvement potential: ${d.estimatedImprovement}`,
    ``,
    divider,
    `PRIORITY ACTIONS`,
    divider,
    ...d.priorityActions.map((a, i) => `#${i + 1}  ${a}`),
    ``,
    divider,
    `TITLE (${d.titleScore}/100)`,
    divider,
    `Problems:`,
    ...d.titleProblems.map(p => `  - ${p}`),
    ``,
    `Suggested titles:`,
    ...d.titleSuggestions.map((t, i) => `  ${i + 1}. ${t}`),
    ``,
    divider,
    `DESCRIPTION (${d.descriptionScore}/100)`,
    divider,
    `Problems:`,
    ...d.descriptionProblems.map(p => `  - ${p}`),
    ``,
    `Full rewrite (copy & paste into your listing):`,
    ``,
    d.descriptionRewrite,
    ``,
    divider,
    `AMENITIES (${d.amenityScore}/100)`,
    divider,
    `Strongest: ${d.topAmenities.join(', ')}`,
    ...(d.amenityGaps.length ? [`Consider adding:`, ...d.amenityGaps.map(a => `  - ${a}`)] : []),
    ``,
    divider,
    `GUEST PERSONA (${d.personaScore}/100)`,
    divider,
    `Primary guest type: ${d.primaryPersona}`,
    ...d.personaProblems.map(p => `  - ${p}`),
    `Suggestion: ${d.personaSuggestion}`,
    ``,
    ...(d.competitorInsight ? [divider, `BEST PRACTICES FROM TOP LISTINGS`, divider, d.competitorInsight, ``] : []),
    divider,
    `REVIEWS (${d.reviewScore}/100)`,
    divider,
    `Guests love: ${d.guestLoves.join(', ')}`,
    ...(d.reviewRisks.length ? [`Watch out for:`, ...d.reviewRisks.map(r => `  - ${r}`)] : []),
    ``,
    divider,
    `GUEST SEARCH KEYWORDS`,
    divider,
    `Phrases your target guests likely search for — useful for understanding your audience:`,
    d.seoKeywords.join(', '),
    ``,
    divider,
    `CONVERSION TIPS`,
    divider,
    ...d.conversionTips.map((t, i) => `${i + 1}. ${t}`),
    ``,
    divider,
    `Generated by ListingIQ`,
    `This report analyses your listing's text, title, photos, and presentation. Pricing strategy, calendar management, minimum-stay rules, and demand-based adjustments are outside this tool's scope but significantly impact performance.`,
    `AI-generated results. Use as guidance alongside your own judgement.`,
  ]
  return lines.join('\n')
}

function CopyReportButton({ data, listingUrl }: { data: ReportData; listingUrl?: string }) {
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(buildTextReport(data, listingUrl))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea')
      textarea.value = buildTextReport(data, listingUrl)
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <button
      onClick={handleCopy}
      style={{ fontFamily: 'var(--font-syne)' }}
      className="inline-flex items-center gap-2 px-4 py-2 bg-amber-400 text-stone-900 text-sm font-bold rounded-xl hover:bg-amber-500 transition-colors cursor-pointer tracking-wide shadow-sm"
    >
      {copied ? 'Copied!' : 'Copy report'}
    </button>
  )
}

const ProblemTag = ({ text }: { text: string }) => (
  <span className="inline-block bg-red-50 text-red-800 text-xs px-2.5 py-1 rounded-lg mr-1.5 mb-1.5">{text}</span>
)

const Chip = ({ text }: { text: string }) => (
  <span className="inline-block bg-stone-100 text-stone-700 text-xs px-2.5 py-1 rounded-full mr-1.5 mb-1.5 border border-stone-200">{text}</span>
)

const SuggestionBox = ({ text }: { text: string }) => (
  <div className="bg-stone-50 border-l-2 border-blue-400 rounded-r-xl px-4 py-3 my-3 text-sm text-stone-800 italic">{text}</div>
)

const RowItem = ({ text, color }: { text: string; color: 'red' | 'amber' | 'green' }) => {
  const dot = { red: 'bg-red-400', amber: 'bg-amber-400', green: 'bg-green-500' }[color]
  return (
    <div className="flex items-start gap-2.5 py-1.5 border-b border-stone-100 last:border-0 text-sm">
      <div className={`w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0 ${dot}`} />
      <span>{text}</span>
    </div>
  )
}

function scoreColor(s: number) {
  return s >= 80 ? '#4a7c2f' : s >= 60 ? '#b45309' : '#b91c1c'
}

export default function Report({ data: d, onReset, plan = 'quick-score', isDemo = false, listingUrl = '', initialPhotoResults = null, initialPhotoPreviews = null }: Props) {
  const [photoResults, setPhotoResults] = useState<PhotoAnalysisResult | null>(initialPhotoResults ?? null)
  const [photoPreviews, setPhotoPreviews] = useState<string[]>(initialPhotoPreviews ?? [])
  const [selectedPkg, setSelectedPkg] = useState<string | null>('Premium')

  // Sync photo results when they arrive after initial render
  useEffect(() => {
    if (initialPhotoResults) setPhotoResults(initialPhotoResults)
  }, [initialPhotoResults])
  useEffect(() => {
    if (initialPhotoPreviews?.length) setPhotoPreviews(initialPhotoPreviews)
  }, [initialPhotoPreviews])
  const hasPhotoAnalysis = plan === 'full-audit'
  // Use AI photo score when available, otherwise show count-based score only for Quick Score
  const photoScoreValue = photoResults ? photoResults.overallPhotoScore : null
  // Recalculate overall score including photo analysis (weighted: photos = 15%, others scaled down proportionally)
  const overallScore = photoResults
    ? Math.round(
        d.titleScore * 0.17 +
        d.descriptionScore * 0.22 +
        photoResults.overallPhotoScore * 0.15 +
        d.amenityScore * 0.17 +
        d.personaScore * 0.12 +
        d.reviewScore * 0.17
      )
    : d.overallScore
  const subScores = hasPhotoAnalysis
    ? [
        { label: 'Title', v: d.titleScore },
        { label: 'Description', v: d.descriptionScore },
        { label: 'Photos', v: photoScoreValue },
        { label: 'Amenities', v: d.amenityScore },
        { label: 'Persona', v: d.personaScore },
        { label: 'Reviews', v: d.reviewScore },
      ]
    : [
        { label: 'Title', v: d.titleScore },
        { label: 'Description', v: d.descriptionScore },
        { label: 'Amenities', v: d.amenityScore },
        { label: 'Persona', v: d.personaScore },
        { label: 'Reviews', v: d.reviewScore },
      ]

  return (
    <div className="max-w-2xl mx-auto px-4 pb-20">

      {/* Analyze another + Plan badge */}
      <div className="mb-4 flex items-center justify-center relative">
        <button onClick={onReset} className="absolute left-0 text-sm text-stone-500 hover:text-stone-700 underline">
          ← Analyze another listing
        </button>
        {plan && (
          <span style={{ fontFamily: 'var(--font-syne)' }} className="inline-block bg-stone-900 text-white text-xs font-bold tracking-widest uppercase px-4 py-1.5 rounded-full">
            {plan === 'quick-score' ? 'Quick Score' : 'Full Audit'}{isDemo ? ' · Demo' : ''}
          </span>
        )}
      </div>

      {/* Listing URL + scrape status */}
      {!isDemo && listingUrl && (
        <p className="text-xs text-stone-500 text-center mb-1">
          <a href={listingUrl} target="_blank" rel="noopener noreferrer" className="underline hover:text-stone-700">
            {(() => { try { const u = new URL(listingUrl); return u.origin + u.pathname } catch { return listingUrl } })()}
          </a>
        </p>
      )}
      {!isDemo && d.wasScraped && (
        <p className="text-xs text-stone-500 text-center mb-3">Data extracted from your Airbnb listing page</p>
      )}

      {/* Score hero */}
      <div className="bg-white border border-stone-200 rounded-2xl p-6 mb-4 flex items-center gap-6">
        <ScoreCircle score={overallScore} />
        <div>
          <h2 style={{ fontFamily: 'var(--font-syne)' }} className="text-xl font-bold text-stone-900 mb-1">
            Airbnb listing score
          </h2>
          <p className="text-sm text-stone-600 mb-3 leading-relaxed">{d.summary}</p>
          <div className="flex flex-wrap items-center gap-3">
            <span className="inline-block bg-green-100 text-green-800 text-sm font-medium px-3 py-1.5 rounded-lg">
              Est. improvement potential: {d.estimatedImprovement}
            </span>
            <DownloadPdfButton data={d} photoResults={photoResults} photoPreviews={photoPreviews} listingUrl={listingUrl} />
            <CopyReportButton data={d} listingUrl={listingUrl} />
          </div>
          <p className="text-xs text-stone-500 mt-2">
            Save your report — download the PDF or copy as text before leaving this page.
            {hasPhotoAnalysis && !photoResults && ' PDF will include photo analysis once you upload and analyze your photos below.'}
          </p>
        </div>
      </div>

      {/* Sub scores */}
      <div className={`grid gap-2 mb-4 ${hasPhotoAnalysis ? 'grid-cols-3 sm:grid-cols-6' : 'grid-cols-3 sm:grid-cols-5'}`}>
        {subScores.map(s => (
          <div key={s.label} className="bg-white border border-stone-200 rounded-xl p-3 text-center">
            <div className="text-xs text-stone-600 uppercase tracking-widest mb-1">{s.label}</div>
            {s.v !== null ? (
              <>
                <div style={{ fontFamily: 'var(--font-syne)', color: scoreColor(s.v) }} className="text-xl font-bold">{s.v}</div>
                <div className="h-1 bg-stone-100 rounded-full mt-2 overflow-hidden">
                  <div className="h-full rounded-full" style={{ width: `${s.v}%`, background: scoreColor(s.v) }} />
                </div>
              </>
            ) : (
              <>
                <div style={{ fontFamily: 'var(--font-syne)' }} className="text-sm font-bold text-stone-300 mt-1">—</div>
                <div className="text-[10px] text-stone-400 mt-1">Upload photos</div>
              </>
            )}
          </div>
        ))}
      </div>

      {/* Priority actions */}
      {d.priorityActions?.length > 0 && (
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 mb-4">
          <h3 style={{ fontFamily: 'var(--font-syne)' }} className="text-sm font-bold text-amber-900 uppercase tracking-wide mb-3">
            Priority action plan
          </h3>
          {d.priorityActions.map((a, i) => (
            <div key={i} className="flex items-start gap-3 py-2 border-b border-amber-200 last:border-0 text-sm text-amber-900">
              <span style={{ fontFamily: 'var(--font-syne)' }} className="font-bold text-amber-600 flex-shrink-0">#{i + 1}</span>
              <span>{a}</span>
            </div>
          ))}
        </div>
      )}

      {/* Title */}
      <ReportSection title="Title optimization" score={d.titleScore} defaultOpen>
        <div className="mt-3">
          <div className="mb-3">{d.titleProblems.map((p, i) => <ProblemTag key={i} text={p} />)}</div>
          <p className="text-xs text-stone-600 uppercase tracking-wide mb-1">Suggested titles</p>
          {d.titleSuggestions.map((t, i) => <SuggestionBox key={i} text={t} />)}
        </div>
      </ReportSection>

      {/* Description */}
      <ReportSection title="Description quality" score={d.descriptionScore}>
        <div className="mt-3">
          <div className="mb-3">{d.descriptionProblems.map((p, i) => <ProblemTag key={i} text={p} />)}</div>
          <p className="text-xs text-stone-600 uppercase tracking-wide mb-1">Full rewrite — copy & paste into your listing</p>
          <div className="bg-stone-50 border border-stone-200 rounded-xl px-5 py-4 my-3 text-sm text-stone-800 leading-relaxed whitespace-pre-line">
            {d.descriptionRewrite}
          </div>
        </div>
      </ReportSection>

      {/* Photos — only show for Quick Score as general tips; Full Audit gets AI Photo Analysis instead */}
      {!hasPhotoAnalysis && (
        <ReportSection title="Photo tips" score={null}>
          <div className="mt-3">
            <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Photos top-performing listings in your market include</p>
            {d.missingPhotos.map((m, i) => <RowItem key={i} text={m} color="amber" />)}
            <p className="text-xs text-stone-600 italic mt-3">General recommendations based on your property type — upgrade to Full Audit for individual photo scoring, reorder suggestions, and retake instructions.</p>
          </div>
        </ReportSection>
      )}

      {/* AI Photo Analysis — Full Audit only */}
      {hasPhotoAnalysis && isDemo && (
        <div className="bg-white border border-stone-200 rounded-2xl p-5 mb-4">
          <div className="flex items-center justify-between mb-3">
            <h3 style={{ fontFamily: 'var(--font-syne)' }} className="text-sm font-bold text-stone-900">
              AI Photo Analysis
            </h3>
            <span className="text-xs bg-blue-50 text-blue-700 px-2.5 py-1 rounded-lg font-medium">
              Full Audit
            </span>
          </div>
          <p className="text-sm text-stone-600 mb-4">
            Upload up to 10 listing photos for individual scoring, reorder suggestions, and retake instructions.
          </p>
          <div className="grid grid-cols-3 gap-3 mb-4">
            {[
              { label: 'Living Room', score: 82, verdict: 'keep', img: '/demo/living-room.jpg', reason: 'Spacious feel with great natural light — strong booking driver.' },
              { label: 'Kitchen', score: 61, verdict: 'retake', img: '/demo/kitchen.jpg', reason: 'Dishes in sink and dim lighting make it feel uninviting. Clear counters and shoot with overhead lights on.' },
              { label: 'Bedroom', score: 74, verdict: 'keep', img: '/demo/bedroom.jpg', reason: 'Bed looks great — white linens give a clean, hotel-like feel.' },
              { label: 'Bathroom', score: 45, verdict: 'retake', img: '/demo/bathroom.jpg', reason: 'Mirror selfie visible, toiletries cluttering counter. Remove items, shoot from doorway to avoid reflections.' },
              { label: 'Exterior', score: 88, verdict: 'keep', img: '/demo/exterior.jpg', reason: 'Strong curb appeal with clean landscaping — ideal hero photo for search results.' },
              { label: 'Patio', score: 70, verdict: 'keep', img: '/demo/patio.jpg', reason: 'Relaxing outdoor space with greenery — adds lifestyle appeal.' },
            ].map((photo, i) => (
              <div key={i} className="bg-stone-50 border border-stone-200 rounded-xl p-3 text-center">
                <img src={photo.img} alt={photo.label} className="w-full h-16 object-cover rounded-lg mb-2" />
                <div className="text-xs text-stone-600 mb-1">{photo.label}</div>
                <div style={{ fontFamily: 'var(--font-syne)', color: scoreColor(photo.score) }} className="text-sm font-bold">{photo.score}</div>
                <span className={`inline-block text-[10px] px-1.5 py-0.5 rounded mt-1 mb-1.5 font-medium ${
                  photo.verdict === 'keep' ? 'bg-green-50 text-green-700' :
                  'bg-red-50 text-red-700'
                }`}>
                  {photo.verdict}
                </span>
                <p className="text-[11px] text-stone-600 leading-tight mt-1">{photo.reason}</p>
              </div>
            ))}
          </div>
          <div className="bg-stone-50 border border-stone-200 rounded-xl p-4">
            <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Suggested cover photo</p>
            <p className="text-sm text-stone-700">Use the Exterior shot as your cover photo — it scored highest (88) and creates a strong first impression in search results.</p>
          </div>
          <p className="text-xs text-stone-600 text-center mt-3 italic">Demo data — upload your real photos for personalized analysis</p>
        </div>
      )}

      {/* Real photo upload — Full Audit paid users */}
      {hasPhotoAnalysis && !isDemo && (
        <div className="mb-4">
          <PhotoUploader
            listingContext={{
              title: d.summary,
              description: d.descriptionRewrite,
              amenities: d.topAmenities,
              missingPhotos: d.missingPhotos,
            }}
            onResults={setPhotoResults}
            onPreviews={setPhotoPreviews}
            initialResults={initialPhotoResults}
            initialPreviews={initialPhotoPreviews}
          />
        </div>
      )}

      {/* Amenities */}
      <ReportSection title="Amenity strength" score={d.amenityScore}>
        <div className="mt-3">
          <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Your strongest amenities</p>
          <div className="mb-3">{d.topAmenities.map((a, i) => <Chip key={i} text={a} />)}</div>
          {d.amenityGaps.length > 0 && (
            <>
              <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Consider adding</p>
              {d.amenityGaps.map((a, i) => <RowItem key={i} text={a} color="amber" />)}
            </>
          )}
        </div>
      </ReportSection>

      {/* Guest persona */}
      <ReportSection title="Guest persona match" score={d.personaScore}>
        <div className="mt-3">
          <p className="text-sm mb-3">Primary guest type: <strong>{d.primaryPersona}</strong></p>
          <div className="mb-3">{d.personaProblems.map((p, i) => <ProblemTag key={i} text={p} />)}</div>
          <SuggestionBox text={d.personaSuggestion} />
        </div>
      </ReportSection>

      {/* Competitor insight */}
      {d.competitorInsight && (
        <div className="bg-blue-50 border border-blue-200 rounded-2xl p-5 mb-4">
          <h3 style={{ fontFamily: 'var(--font-syne)' }} className="text-sm font-bold text-blue-900 uppercase tracking-wide mb-2">
            Best practices from top-performing listings
          </h3>
          <p className="text-sm text-blue-900 leading-relaxed">{d.competitorInsight}</p>
        </div>
      )}

      {/* Reviews */}
      <ReportSection title="Review sentiment" score={d.reviewScore}>
        <div className="mt-3">
          <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Guests mention positively</p>
          <div className="mb-3">{d.guestLoves.map((g, i) => <Chip key={i} text={g} />)}</div>
          {d.reviewRisks.length > 0 && (
            <>
              <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Watch out for</p>
              {d.reviewRisks.map((r, i) => <RowItem key={i} text={r} color="amber" />)}
            </>
          )}
        </div>
      </ReportSection>

      {/* SEO */}
      <ReportSection title="Keywords & conversion tips" score={null}>
        <div className="mt-3">
          <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Phrases your target guests search for</p>
          <div className="mb-3">{d.seoKeywords.map((k, i) => <Chip key={i} text={k} />)}</div>
          <p className="text-[11px] text-stone-600 mb-3 leading-relaxed">These help you understand your audience and use natural language in your listing. Airbnb ranks listings primarily by response rate, reviews, pricing, and listing completeness — not keyword density.</p>
          <p className="text-xs text-stone-600 uppercase tracking-wide mb-2">Booking conversion tips</p>
          {d.conversionTips.map((t, i) => <RowItem key={i} text={t} color="green" />)}
        </div>
      </ReportSection>

      {/* Upgrade prompt */}
      {plan === 'quick-score' && (
        <div className="bg-white border border-stone-200 rounded-2xl p-6 mt-6">
          <p className="text-xs text-stone-600 uppercase tracking-widest font-bold mb-4 text-center">
            {isDemo ? 'Get more from ListingIQ' : 'Upgrade your report'}
          </p>
          <div className="max-w-xs mx-auto">
            <div className="rounded-xl p-4 text-center border-2 border-stone-900">
              <div style={{ fontFamily: 'var(--font-syne)' }} className="text-sm font-bold text-stone-900 mb-1">Full Audit</div>
              <div className="mb-2">
                <span style={{ fontFamily: 'var(--font-syne)' }} className="text-xl font-bold text-stone-900">$49</span>
              </div>
              <ul className="text-xs text-stone-600 space-y-1 mb-3 text-left inline-block">
                <li className="flex gap-1.5"><span className="text-green-600">✓</span>Everything in Quick Score</li>
                <li className="flex gap-1.5"><span className="text-green-600">✓</span>AI photo analysis (10 photos)</li>
                <li className="flex gap-1.5"><span className="text-green-600">✓</span>Photo reorder + retake instructions</li>
              </ul>
              {isDemo ? (
                <button
                  onClick={() => window.location.href = '/?demo=full-audit'}
                  style={{ fontFamily: 'var(--font-syne)' }}
                  className="w-full py-2.5 bg-stone-900 text-white text-xs font-bold rounded-lg hover:bg-stone-700 transition-colors tracking-wide"
                >
                  Try Full Audit demo →
                </button>
              ) : (
                <button
                  onClick={() => window.location.href = `/api/checkout-redirect?plan=full-audit&url=${encodeURIComponent(listingUrl)}&upgrade=1`}
                  style={{ fontFamily: 'var(--font-syne)' }}
                  className="w-full py-2.5 bg-stone-900 text-white text-xs font-bold rounded-lg hover:bg-stone-700 transition-colors tracking-wide"
                >
                  Get Full Audit · $49
                </button>
              )}
            </div>
          </div>
          {!isDemo && (
            <p className="text-xs text-stone-600 text-center mt-3">
              Secure checkout via Stripe · One-time payment
            </p>
          )}
        </div>
      )}

      {/* Human optimization upsell */}
      <div className="bg-white border border-stone-200 rounded-2xl p-6 mt-6">
        <div className="text-center mb-5">
          <p className="text-xs text-stone-600 uppercase tracking-widest font-bold mb-2">Want a human expert instead?</p>
          <h3 style={{ fontFamily: 'var(--font-syne)' }} className="text-lg font-bold text-stone-900 mb-1">
            Airbnb Listing Optimization
          </h3>
          <p className="text-sm text-stone-600 max-w-sm mx-auto">
            Get a professional, hands-on optimization from a real Airbnb expert — ready-to-use copy, photo guidance, pricing strategy, and more.
          </p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5">
          {[
            {
              name: 'Standard',
              price: '$68',
              color: 'text-amber-700',
              href: 'https://redhiker.gumroad.com/l/listing-review',
              features: ['Listing analysis', '1 document', 'Delivered in 48hrs'],
            },
            {
              name: 'Premium',
              price: '$125',
              color: 'text-stone-700',
              popular: true,
              href: 'https://redhiker.gumroad.com/l/listing-review-done-for-you',
              features: ['Listing analysis', 'Ready-to-use copy', '2 documents'],
            },
            {
              name: 'VIP Zoom',
              price: '$225',
              color: 'text-blue-700',
              href: 'https://redhiker.gumroad.com/l/listing-review-vip-zoom',
              features: ['4 documents', '60-min Zoom session', 'Photo & visual guide'],
            },
            {
              name: 'Partner',
              price: '$495',
              color: 'text-green-700',
              href: 'https://redhiker.gumroad.com/l/listing-partner',
              features: ['Everything in VIP', '30-day support', 'Weekly check-ins'],
            },
          ].map((pkg) => {
            const isSelected = selectedPkg === pkg.name
            return (
              <div
                key={pkg.name}
                onClick={() => setSelectedPkg(pkg.name)}
                className={`rounded-xl p-3 text-center cursor-pointer transition-all ${
                  isSelected
                    ? 'border-2 border-stone-900 bg-stone-50 shadow-sm'
                    : 'border border-stone-200 hover:border-stone-300'
                }`}
              >
                <div style={{ fontFamily: 'var(--font-syne)' }} className={`text-[10px] font-bold uppercase tracking-widest mb-1 ${pkg.color}`}>
                  {pkg.name}
                </div>
                <div style={{ fontFamily: 'var(--font-syne)' }} className="text-xl font-bold text-stone-900 mb-2">
                  {pkg.price}
                </div>
                <ul className="text-[11px] text-stone-600 space-y-1 text-left">
                  {pkg.features.map((f, i) => (
                    <li key={i} className="flex gap-1">
                      <span className="text-green-600 flex-shrink-0">&#10003;</span>{f}
                    </li>
                  ))}
                </ul>
              </div>
            )
          })}
        </div>

        {(() => {
          const pkgs = [
            { name: 'Standard', href: 'https://redhiker.gumroad.com/l/listing-review' },
            { name: 'Premium', href: 'https://redhiker.gumroad.com/l/listing-review-done-for-you' },
            { name: 'VIP Zoom', href: 'https://redhiker.gumroad.com/l/listing-review-vip-zoom' },
            { name: 'Partner', href: 'https://redhiker.gumroad.com/l/listing-partner' },
          ]
          const selected = pkgs.find(p => p.name === selectedPkg)
          return selected ? (
            <div className="text-center">
              <a
                href={selected.href}
                target="_blank"
                rel="noopener noreferrer"
                style={{ fontFamily: 'var(--font-syne)' }}
                className="inline-block bg-stone-900 text-white text-xs font-bold tracking-wide px-6 py-3 rounded-xl hover:bg-stone-700 transition-colors"
              >
                Get {selected.name} →
              </a>
            </div>
          ) : null
        })()}

        <p className="text-[11px] text-stone-600 text-center mt-4">
          One listing per purchase · Delivered within 48 hours · Available in any language
        </p>
      </div>


      {/* Disclosure */}
      <div className="text-[11px] text-stone-600 text-center mt-6 leading-relaxed max-w-md mx-auto space-y-2 font-bold">
        <p>
          This report analyses your listing&apos;s text, title, photos, and presentation. Pricing strategy, calendar management, minimum-stay rules, and demand-based adjustments are outside this tool&apos;s scope but significantly impact performance.
        </p>
        <p>
          Results are AI-generated, may not be fully accurate, and can vary between runs for the same listing. This is not financial advice. Use results as guidance alongside your own judgement. ListingIQ is not affiliated with Airbnb.
        </p>
        <p className="text-stone-500 mt-2">v{APP_VERSION}</p>
      </div>
    </div>
  )
}
